config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :transfers, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ethereum_api.rb
class EthereumApi
  TRUFFLE_PATH = "#{Dir.pwd}/truffle/"
  GANACHE_URL = 'HTTP://127.0.0.1:7545'
  attr_accessor :contract, :client

  def initialize
    self.client = Ethereum::HttpClient.new(GANACHE_URL)
    create_default_token! if Token.count.zero?
    token = Token.first
    self.contract = Ethereum::Contract.create(name: "AppToken", truffle: { paths: [ TRUFFLE_PATH ] }, client: @client, address: token.token_address)
  end

  def create_default_token!
    self.client = Ethereum::HttpClient.new(GANACHE_URL)
    self.contract = Ethereum::Contract.create(name: "AppToken", truffle: { paths: [ TRUFFLE_PATH ] }, client: @client)
    token = Token.new(
      name: Token::DEFAULT_NAME,
      symbol: Token::DEFAULT_SYMBOL,
      total_supply: Token::DEFAULT_TOTAL_SUPPLY
    )
    address = contract.deploy_and_wait(token.name, token.symbol, token.total_supply)
    token.token_address = address
    token.save!
  end

  def get_accounts
    client.eth_accounts['result']
  end

  def transfer(address, amount)
    begin
      contract.transact_and_wait.transfer(address, amount)
    rescue => e
      Rails::logger::debug("Error token transfer. message: #{e.message}")
      false
    end
  end
end

app/models/token.rb
class Token < ApplicationRecord
  DEFAULT_NAME = ENV['DEFAULT_TOKEN_NAME']
  DEFAULT_SYMBOL = ENV['DEFAULT_TOKEN_SYMBOL']
  DEFAULT_TOTAL_SUPPLY = ENV['DEFAULT_TOKEN_TOTAL_SUPPLY']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  TRUFFLE_PATH = "#{Dir.pwd}/truffle/"
  GANACHE_URL = 'HTTP://127.0.0.1:7545'

  def index
    @ethereum_api = EthereumApi.new
    @token = Token.first
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  TRUFFLE_PATH = "#{Dir.pwd}/truffle/"
  GANACHE_URL = 'HTTP://127.0.0.1:7545'

  def new
    @address = params[:address]
    @token = Token.first
  end

  def create
    @address = transfer_params[:address]
    amount = transfer_params[:amount]
    @ethereum_api = EthereumApi.new
    if @ethereum_api.transfer(@address, amount.to_i)
      redirect_to root_path, notice: '送金に成功しました。'
    else
      @token = Token.first
      flash[:alert] = '送金に失敗しました。'
      render :new
    end
  end

  private

    def transfer_params
      params.require(:transfer).permit(:address, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
- accounts = @ethereum_api.get_accounts
- user1_address = accounts[0]
- user2_address = accounts[1]
%h3
  = @token.name
  送金テスト
%p
  総供給量:
  = @ethereum_api.contract.call.total_supply()
  = @token.symbol
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          アドレス1：
          = user1_address
      .panel-body
        .div
          %label
            トークン残高：
          %span
            = @ethereum_api.contract.call.balance_of(user1_address)
            = @token.symbol
        .div
          %label
            Ether残高：
          %span
            - formatter = Ethereum::Formatter.new
            = formatter.from_wei(Integer(@ethereum_api.client.eth_get_balance(user1_address)['result'])).to_f
            ETH
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          アドレス2：
          = user2_address
      .panel-body
        .div
          %label
            トークン残高：
          %span
            = @ethereum_api.contract.call.balance_of(user2_address)
            = @token.symbol
        .div
          %label
            Ether残高：
          %span
            - formatter = Ethereum::Formatter.new
            = formatter.from_wei(Integer(@ethereum_api.client.eth_get_balance(user2_address)['result'])).to_f
            ETH
= link_to fa_icon('arrow-right', text: 'アドレス2に送金する'), new_transfer_path(address: user2_address)

app/views/layouts/_messages.html.haml
- flash.each do |name, message|
  - if message.is_a?(String) && !Rails.env.test?
    - case name.to_s
    - when 'notice'
      :javascript
        toastr.success('#{message}');
    - when 'alert'
      :javascript
        toastr.error('#{message}');

app/views/layouts/_navigation.html.haml
:ruby

%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        %strong Ethereum Token Sample

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EthereumTokenSample
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/messages'
    %header
      = render 'layouts/navigation'
    %main{role: 'main'}
      .container
        = yield

app/views/transfers/new.html.haml
%h3 送金
= simple_form_for :transfer, url: transfers_path do |f|
  %label 送金先アドレス
  %p= @address
  = f.input :address, as: :hidden, input_html: { value: @address }
  = f.input :amount, as: :integer, label: "送金量(#{@token.symbol})", input_html: { class: 'transfer__amount-form' }
  = f.button :submit, '送金する', class: 'btn btn-primary', data: { disable_with: '送金中...' }